name: app_cat_pragma
description: "A app de prueba tecnica para pragma."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  #Data
  http: ^1.5.0
  url_launcher: ^6.3.2
  #State Management
  get: ^4.7.2
  #Navigator 
  go_router: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
